### ISSUE TITLE
replace() function expects argument to be of string type, but the variable "size" is of type int.

### ISSUE THREAD

**Issue by ghost** [SynBioHub/Plugin-Visual-Test#7]
The fix is to replace line 68 with the following code instead
```python
result = result.replace("SIZE_REPLACE", str(size))
```
https://github.com/SynBioHub/Plugin-Visual-Test/blob/b80e2d84e485a563a47078ef4d39190f174323cf/app.py#L68

**Comment by JMante1** [comment]
this has been fixed
